jobs:
  - script: |
      multibranchPipelineJob('DPC') {
        description("Dummy DPC application")
        branchSources {
          git {
              id('dpc_src')
              credentialsId('github-access')
              remote('https://github.com/rendevor/dpc_src.git')
              includes("master main v.*")
          }
          factory {
            workflowBranchProjectFactory {
              scriptPath('dpc.Jenkinsfile')
            }
          }
        }
      }
