version: '3.3'

services:
  jenkins:
    build:
      context: "."
      dockerfile: "jenkins.Dockerfile"
    environment:
      JAVA_OPTS="-Xms512m \
        -Xmx1g \
        -XX:+UseG1GC \
        -XX:+ExplicitGCInvokesConcurrent \
        -XX:+ParallelRefProcEnabled \
        -XX:+UseStringDeduplication \
        -XX:+UnlockExperimentalVMOptions \
        -XX:G1NewSizePercent=20 \
        -XX:+UnlockDiagnosticVMOptions \
        -XX:G1SummarizeRSetStatsPeriod=1"  
    ports: 
      - 8080:8080
      - 50000:50000
    volumes: 
      - /home/ids/dpc1/dpc_core/jenkins_casc:/var/jenkins_casc
      - /home/ids/dpc1/dpc_core/jenkins_home:/var/jenkins_home
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_casc
    secrets: 
      - jenkins_github_access
    user: 1000:1000
secrets:
  jenkins_github_access:
    file: .dpc_secret_jenkins_github_access

volumes:
  jenkins_home:
  jenkins_casc:
